#!/bin/bash
#SBATCH --ntasks=75
#SBATCH --array=0-0
#SBATCH --exclude=hpc[1-13]

module load gcc/gcc11

i=$SLURM_ARRAY_TASK_ID

# setup result directory
RESULT_DIR="RESULT${i}/"

mkdir $RESULT_DIR

#input file name
INPUT_FILE="${pwd}input${i}.dat"

#file at which output is redirected
OUT_FILE="${pwd}output${i}.dat"

#restart file (generated by running this script without a restart)
RESTART_FILE="RESULT0/restart8"
	
D1_p_star=$(bc <<<"-0.5")

#generate a new input file  

# output problem parameters to input file 
#**************** Problem Parameters *************************
printf "D2 = 0.4\n" > $INPUT_FILE
printf "beta=4.0\n" >> $INPUT_FILE
printf "alpha = 0.5\n" >> $INPUT_FILE
printf "D1_star = 0.5\n" >> $INPUT_FILE
printf "D1_p_star = ${D1_p_star}\n" >>  $INPUT_FILE
printf "D_inf_0 = 0.1\n" >> $INPUT_FILE
printf "Lu = 6.0\n" >>  $INPUT_FILE
printf "Lx = 8.0\n" >>  $INPUT_FILE
	
#**************** kinetic parameters ***********************
printf "a = 0.3\n" >>  $INPUT_FILE
printf "L = 10.0\n" >>  $INPUT_FILE
printf "K = 10.0\n" >>  $INPUT_FILE
printf "lambda = 2.0\n" >>  $INPUT_FILE
printf "m=25.0\n" >>  $INPUT_FILE
printf "epsilon = 4.0e-2\n" >>  $INPUT_FILE

#****************** numerical parameters **********************
printf "Nu_density = 300\n" >>  $INPUT_FILE
printf "Nu_helm = 1\n" >>  $INPUT_FILE
printf "Nx = 50\n" >>  $INPUT_FILE
printf "rho_eval = ${Lx}\n" >> $INPUT_FILE

#mpirun ./steady_solve $INPUT_FILE $RESULT_DIR --restart-file $RESTART_FILE > $OUT_FILE #with restart
mpirun ./steady_solve $INPUT_FILE $RESULT_DIR > $OUT_FILE	#without restart




